# config.py

BINANCE_API_KEY = "Zy0M609mbjFTQOksRx0BML4bRQzyXGRO9d3RTIiWLmHDylSt5xzfQdjc84giFVZM"
BINANCE_SECRET = "GP0OdHCWaF37scu0HqNmHoVz4eMiV8vvz9WDgQDfwyTULqNrLmhxRvXZ3zNQGbQE"

TELEGRAM_TOKEN = "7951632552:AAFOBdhFlEW3HafWCzi6-Us0uSUkIKhM4TI"
TELEGRAM_CHAT_ID = 1291424537
ALLOWED_CHAT_ID = 1291424537  # cùng giá trị để chặn người lạ

TRADE_SYMBOLS = ["ETH/USDT", "BTC/USDT"]
TRADE_PERCENT = 0.05  # fallback nếu không dùng vốn cố định

USE_FIXED_CAPITAL = True
FIXED_USDT_PER_ORDER = 15

# Quản lý vốn đầu tư giới hạn
USE_CAPITAL_LIMIT = True
CAPITAL_LIMIT = 500

USE_GOOGLE_SHEET = False
SHEET_WEBHOOK = ""

DAILY_MAX_LOSS = -30  # cho phép lỗ tối đa 30 USDT/ngày
